#!/bin/bash
#
# EMI Registry
### BEGIN INIT INFO
# Provides:          emi-registry
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       EMI Service Registry
### END INIT INFO


# Source function library.
. /lib/lsb/init-functions

NAME="EMIR"

#
# Read basic configuration parameters
#
. /etc/emi/emir/startup.properties


start() {
        log_daemon_msg "Starting $NAME"
        start-stop-daemon --start --chuid $EMIR_USER --exec "$START"
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch "/var/lock/$SERVICE"
        log_end_msg $RETVAL
        echo
        return $RETVAL

}
stop() {
         log_daemon_msg "Stopping $NAME"
         echo
         su $EMIR_USER -p "$STOP"
         log_end_msg $?
         rm -f "/var/lock/$SERVICE"
}

status(){
         if [ -a "$PID" ]; then
                 status_of_proc -p "$PID" "$SERVICE" "$NAME"
         else
                 log_failure_msg "$SERVICE is not running"
         fi
}



# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status 
	;;
  restart)
	stop
	start
	;;
   force-reload)
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|force-reload|help}"
	exit 1
esac

exit $RETVAL
