#!/usr/bin/env python

# Dependcies:
#   sudo yum install python-simplejson

import logging

from time   import sleep
from sys    import exit, path
from os     import devnull

path.insert(0, '/usr/lib/emi/emird')
path.insert(0, '/usr/lib64/emi/emird')

from daemon import Daemon
from EMIR import EMIRConfiguration, EMIRClient

class emird(Daemon):
  def __init__(self, pid_file, config_file, log_file):

    # Initialize EMIR related components
    try: 
      self.config = EMIRConfiguration(config_file) 
    except Exception, inst: 
      print inst 
      exit(1) 
    self.client = EMIRClient(self.config)

    # Initialize 'emird' logger object
    self.logger = logging.getLogger('emird')
    logger_handler = logging.FileHandler(log_file)
    logger_formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    logger_handler.setFormatter(logger_formatter)
    self.logger.addHandler(logger_handler)
    self.logger.setLevel(self.config.loglevel)

    # Check wether there is any service entry to be registered
    if not self.config.getServiceEntries():
      self.logger.info("No service entries has been defined")
      exit(0)

    # Check whether the EMIR is URL is valid and the service is available
    try:
      self.logger.debug("EMIR service on url '%s://%s:%s' is running since %s" % (self.config.protocol, self.config.host, self.config.port, self.client.ping()))
    except:
      self.logger.error("Connection failed to %s://%s:%s" % (self.config.protocol, self.config.host, self.config.port))
      exit(1)

    # Call parent's constructor to daemonize the process
    super(emird,self).__init__(pid_file, devnull, devnull, devnull, '/tmp')

  def run(self):
    # Try to send registration message. If do not manage to fall back
    # to update. For example because of already existing registration
    # entries.
    try:
      self.logger.debug('Registering service entries')
      self.client.register()
    except Exception, ex:
      try:
        self.logger.debug('Falling back to initial service entry update')
        self.client.update()
      except Exception, ex:
        self.logger.error("Registration failed: %s" % ex)
        exit(1)

    # After the successful initial registration wait the selected time
    # (where the configured period is given in minutes so have to be
    # multiplied by 60) then try to send an update message.
    sleep(self.config.period * 60)
    while self.daemon_alive:
      try:
        self.logger.debug('Periodical registration update')
        self.client.update()
      except Exception, ex:
        self.logger.error("Update failed: %s" % ex)
        exit(1)
      sleep(self.config.period * 60)

    # Delete registered entries
    try:
      self.logger.debug('Deleting reqistered entries')
      self.client.delete()
    except Exception, ex:
      self.logger.error('Error during deletion: %s' % ex)
      exit(1)
    # Call parents stop() function to stop the daemon itself

    self.stop()

if __name__ == "__main__":

  from optparse import OptionParser
  parser = OptionParser()
  # Location of the configuration file.
  parser.add_option("-c", "--config-file", dest="config_file", default='/etc/emi/emird/emird.ini',
                    help="""the path of the config file
                    [default: %default]""")
  # Location of the pid file.
  parser.add_option("-p", "--pid-file", dest="pid_file", default='/var/run/emi/emird/emird.pid',
                    help="""the path of the PID file
                    [default: %default]""")
  # Location of the log file.
  parser.add_option("-l", "--log-file", dest="log_file", default='/var/log/emi/emird/emird.log',
                    help="""the path of the log file
                    [default: %default]""")
  # The daemon is started in foreground mode ( = 1) or in the
  # background ( = 0 )
  parser.add_option("-f", "--foreground", action="store_true", dest="foreground", default=False,
                    help="run in foreground [default: %default]")
  (options, args) = parser.parse_args()

  # Creating and starting the daemon class and process
  myDaemon = emird(options.pid_file, options.config_file, options.log_file)

  if options.foreground:
    myDaemon.run()
  else:
    myDaemon.start()

  exit(0)

