#!/bin/bash
#
# EMIRD
#
# Source function library.
. /etc/rc.d/init.d/functions

NAME="EMIRD"

#This must be equal to this file name
SERVICE=emird
DAEMON=/usr/bin/emird
EMIRD_USER=emi
LASTPID=/var/run/emi/emird/emird.pid

# See how we were called.
RETVAL=0
case "$1" in
  start)
        if [ -f $LASTPID ]; then
          status -p "$LASTPID" "$SERVICE"
          RETVAL=$?
        else
          runuser -s /bin/bash -c "$DAEMON" "$EMIRD_USER"
          RETVAL=$?
          echo -n "$NAME startup"
          [ "$RETVAL" -eq 0 ] && success || failure 
          echo
        fi
        ;;
  stop)
        kill -s SIGTERM `cat $LASTPID` >/dev/null 2>&1
        RETVAL=$?
        echo -n "$NAME shutdown"
        if [ "$RETVAL" -eq 0 ]; then
          until [ ! -f $LASTPID ]; do
            sleep 2
          done
          success 
        else
          failure
        fi
        echo
        ;;
  status)
        status -p "$LASTPID" "$SERVICE"
        RETVAL=$?
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|help}"
        exit 1
esac

exit $RETVAL
