#!/bin/bash
#
# EMIR
#
# chkconfig: 235 96 04
# description: EMIR

# Source function library.
. /etc/rc.d/init.d/functions

NAME="EMIR"

#This must be equal to this file name
SERVICE=emir
EMIR_USER=emir
START=/usr/sbin/emir-start.sh
STOP=/usr/sbin/emir-stop.sh
LASTPID=/var/run/emir/emir.pid


start() {
	echo -n "Starting $NAME: "
	daemon --user $EMIR_USER "$START"
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch "/var/lock/subsys/$SERVICE"
	echo
	return $RETVAL
}
stop() {
	echo -n $"Stopping $NAME: "
	runuser -s /bin/sh -c "$STOP" $EMIR_USER 
	rm -f "/var/lock/subsys/$SERVICE"
	echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p "$LASTPID" "$SERVICE"
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|help}"
	exit 1
esac

exit $RETVAL
